<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Author>wirumn</Author>
    <Name>CosmicBaiter</Name>
    <Punchline>Automatically equips Refined Cosmic Mayfly for Stellar Missions.</Punchline>
    <Description>Equips Refined Cosmic Mayfly automatically when you start a Cosmic Exploration fishing mission.</Description>
    <Tags>fishing;cosmic exploration</Tags>
    <AcceptsFeedback>false</AcceptsFeedback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.1.6" />
    <PackageReference Include="ImGui.NET" Version="1.90.0.1" />
  </ItemGroup>
</Project>
